# Generated by Django 5.1.1 on 2024-09-28 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=15)),
                ('is_on_duty', models.BooleanField(default=False)),
                ('duty_coord_lat', models.FloatField()),
                ('duty_coord_long', models.FloatField()),
                ('supervisor_no', models.CharField(max_length=15)),
                ('radius_of_duty', models.FloatField()),
                ('duty_time_start', models.DateTimeField()),
                ('duty_time_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='officer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.officer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.supervisor'),
        ),
    ]
