# Generated by Django 5.1.1 on 2024-09-28 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_officer_supervisor_userprofile_officer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='officer',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='duty_coord_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='duty_coord_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='duty_time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='duty_time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='radius_of_duty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
