# Generated by Django 5.1.1 on 2024-09-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_officer_supervisor_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
