# Generated by Django 5.1.1 on 2024-09-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_officer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
